apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-blog-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news-blog
  template:
    metadata:
      name: news-blog
      labels:
        app: news-blog
    spec:
      containers:
      - name: news-blog
        image: aluracursos/portal-noticias:1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: news-blog-configmap
