apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: news-blog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-blog-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resources
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50