apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-blog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news-blog
  template:
    metadata:
      name: news-blog
      labels:
        app: news-blog
    spec:
      containers:
      - name: news-blog
        image: aluracursos/portal-noticias:1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: news-blog-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /inserir_noticias.php
            port: 80
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 10m
