apiVersion: v1
kind: Pod
metadata:
  name: news-system
  labels:
    app: news-system
spec:
  containers:
    - name: news-system-pod
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: db-system
