apiVersion: v1
kind: Pod
metadata:
  name: news-blog
  labels:
    app: news-blog
spec:
  containers:
  - name: news-blog
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: news-blog-configmap