apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /alura-k8s
          name: k8s-volume
    - name: jenkins-container
      image: jenkins/jenkins:latest
      volumeMounts:
        - mountPath: /alura-k8s
          name: k8s-volume
  volumes:
    - name: k8s-volume
      hostPath:
        path: /minik8s-volume
        type: DirectoryOrCreate