apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysql
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: t0malexander/k8s-helm-db-backup:v1
              imagePullPolicy: IfNotPresent
              env:
                - name: MYSQL_ENV_DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: dados
                      key: MYSQL_ENV_DB_HOST

                - name: MYSQL_ENV_DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: senhas
                      key: MYSQL_ENV_DB_PASS

          restartPolicy: OnFailure
