apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-pv
spec:
  capacity:
    storage: 1Mib
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  getPersistentDisk:
    pdName: pv-disk
  storageClassName: standard